### ISSUE TITLE
spark.emit('custom-event', ...) is captured by primus.on('data', ...) on the client side

### ISSUE THREAD

**Issue by op1ekun** [primus/primus-emit#2]

**Comment by jcrugzz** [comment]
Could you provide a reproducible test case with the versions of the modules?

**Comment by op1ekun** [comment]
Primus version: 2.4.12
primus-emit version: 0.1.2

Server side

    var Primus = require('primus');

    var primus = Primus.createServer({
        port: 11235,
        pathname: '/',
        transformer: 'websockets'
    });

    primus.use('emit', require('primus-emit'));

    primus.on('connection', function(client) {

       console.log('client ' + client.id + ' has connected to the server');

       primus.forEach(function handleSpark(spark, id, connections) {
            if (spark.id !== client.id) {
                spark.emit('clientConnected', spark.id);
            }        
        });
    });


Client side

    var primus = new Primus('ws://ridealong:11235');

    primus.on('data', function(data) {  
        console.log('server response', data);
        addRow(data);
    });

    primus.on('clientConnected', function() {
         console.log('clientConnected', arguments);
    });


My `clientConnected` is captured by `data` listener (dump from chrome dev console):

    Object {emit: Array[2]}
    emit: Array[2]
         0: "clientConnected"
         1: "1432232165877$3"
         length: 2

**Comment by 3rd-Eden** [comment]
Did you recompile the client after adding the primus-emit plugin

Arnout Kazemier

**Comment by lpinca** [comment]
@op1ekun I can't reproduce it.
Here is my test case:
```js
'use strict';

var Primus = require('primus')
  , fs = require('fs')
  , primus
  , server;

server = require('http').createServer(function (req, res) {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  fs.createReadStream(__dirname + '/index.html').pipe(res);
});

primus = new Primus(server, { transformer: 'faye' });
primus.use('emit', 'primus-emit');

primus.on('connection', function (spark) {
  console.log(spark.id + ' connected');
  primus.forEach(function (socket) {
    if (socket !== spark) socket.emit('clientConnected', spark.id);
  });
});
primus.on('disconnection', function (spark) {
  console.log(spark.id + ' disconnected');
});

server.listen(3000, function () {
  console.log('listening on port 3000');
});
```
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="/primus/primus.js"></script>
    <script>
      (function () {
        var primus = new Primus({ strategy: false });

        primus.on('data', function (data) {
          console.log(data);
        });
        primus.on('clientConnected', function (id) {
          console.log(id);
        });
      })();
    </script>
  </body>
</html>
```

**Comment by lpinca** [comment]
As @3rd-Eden said, make sure that you have rebuilt the client.

**Comment by op1ekun** [comment]
Thanks guys that was the case :) Now I remember the line about "using" plugins before you save the client. In my defense I can only say today is my second day with Primus. Case closed!
